version: '3.8'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      - MYSQL_DATABASE=jetbill
      - MYSQL_ROOT_PASSWORD=jetbill3165880
    ports:
      - '3307:3307'
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
